### ISSUE TITLE
 Optimise Plugin Chart Http Request

### ISSUE THREAD

**Issue by Cuiyansong** [running-elephant/datart#650]
**Is your feature request related to a problem? Please describe.**
Too many duplicate http request on board page, etc

**Additional context**
This feature request aim to discuss and tracking process.

**TODO**
- [x] Reduce duplicate http request in board
- [x] Reuse echart library/instance in order to avoid duplicate request
- [x] Http header cache vs. 3td part http request management library

**Comment by Cuiyansong** [comment]
The http cache have been already used.
